version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=Dana
      - POSTGRES_PASSWORD=PgDana